name: Deploy services
on:
  push:
    branches:
      - main
    paths:
      - 'services/**'
  workflow_dispatch:

jobs:
  deploy-functions:
    name: Deploy functions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['core', 'facebook']
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Deploy Supabase functions
        working-directory: services/${{ matrix.service }}
        run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID
        env:
          SUPABASE_PROJECT_ID: ${{secrets.SUPABASE_PROJECT_ID}}
          SUPABASE_ACCESS_TOKEN: ${{secrets.SUPABASE_ACCESS_TOKEN}}

  run-migrations:
    name: Run migrations
    runs-on: ubuntu-latest
    needs: [deploy-functions]
    strategy:
      matrix:
        service: ['core', 'facebook']
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Push database changes
        working-directory: services/${{ matrix.service }}
        run: supabase db push --project-ref $SUPABASE_PROJECT_ID
        env:
          SUPABASE_PROJECT_ID: ${{secrets.SUPABASE_PROJECT_ID}}
          SUPABASE_ACCESS_TOKEN: ${{secrets.SUPABASE_ACCESS_TOKEN}}
